/*******************************************************************************
 * RefineryWnd generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class RefineryWnd extends UICommonAPI;

const C_ANIMLOOPCOUNT = 1;
const C_ANIMLOOPCOUNT1 = 1;
const C_ANIMLOOPCOUNT2 = 1;
const C_ANIMLOOPCOUNT3 = 1;

var bool procedure1stat;
var bool procedure2stat;
var bool procedure3stat;
var bool procedure4stat;
var ItemInfo RefineItemInfo;
var ItemInfo LifeStoneItemInfo;
var ItemInfo GemstoneItemInfo;
var ItemInfo RefinedITemInfo;
var WindowHandle m_RefineryWnd_Main;
var WindowHandle m_Highlight1;
var WindowHandle m_Highlight2;
var WindowHandle m_Highlight3;
var WindowHandle m_SeletedItemHighlight1;
var WindowHandle m_SeletedItemHighlight2;
var WindowHandle m_SeletedItemHighlight3;
var WindowHandle m_DragBox1;
var WindowHandle m_DragBox2;
var WindowHandle m_DragBox3;
var WindowHandle m_ResultAnimation1;
var WindowHandle m_ResultAnimation2;
var WindowHandle m_ResultAnimation3;
var AnimTextureHandle m_ResultAnim1;
var AnimTextureHandle m_ResultAnim2;
var AnimTextureHandle m_ResultAnim3;
var ButtonHandle m_OkBtn;
var ButtonHandle m_RefineryBtn;
var ButtonHandle m_UnRefineryBtn;
var ItemWindowHandle m_DragboxItem1;
var ItemWindowHandle m_DragBoxItem2;
var ItemWindowHandle m_DragBoxItem3;
var TextBoxHandle m_InstructionText;
var TextBoxHandle m_RefText;
var int m_TargetItemServerID;
var int m_RefineItemServerID;
var int m_GemStoneServerID;
var int m_GemStoneClassID;
var int m_NecessaryGemstoneCount;
var string m_GemstoneName;
var InventoryWnd inventoryWndScript;

function OnLoad()
{
    RegisterEvent(2760);
    RegisterEvent(2770);
    RegisterEvent(2780);
    RegisterEvent(2790);
    RegisterEvent(2800);
    procedure1stat = false;
    procedure2stat = false;
    procedure3stat = false;
    procedure4stat = false;
    m_RefineryWnd_Main = GetHandle("RefineryWnd");
    m_Highlight1 = GetHandle("RefineryWnd.ItemDragBox1Wnd.DropHighlight");
    m_Highlight2 = GetHandle("RefineryWnd.ItemDragBox2Wnd.DropHighlight");
    m_Highlight3 = GetHandle("RefineryWnd.ItemDragBox3Wnd.DropHighlight");
    m_SeletedItemHighlight1 = GetHandle("RefineryWnd.ItemDragBox1Wnd.SelectedItemHighlight");
    m_SeletedItemHighlight2 = GetHandle("RefineryWnd.ItemDragBox2Wnd.SelectedItemHighlight");
    m_SeletedItemHighlight3 = GetHandle("RefineryWnd.ItemDragBox3Wnd.SelectedItemHighlight");
    m_DragBox1 = GetHandle("RefineryWnd.ItemDragBox1Wnd");
    m_DragBox2 = GetHandle("RefineryWnd.ItemDragBox2Wnd");
    m_DragBox3 = GetHandle("RefineryWnd.ItemDragBox3Wnd");
    m_ResultAnimation1 = GetHandle("RefineryWnd.RefineResultAnimation01");
    m_ResultAnimation2 = GetHandle("RefineryWnd.RefineResultAnimation02");
    m_ResultAnimation3 = GetHandle("RefineryWnd.RefineResultAnimation03");
    m_ResultAnim1 = AnimTextureHandle(GetHandle("RefineryWnd.RefineResultAnimation01.RefineResult1"));
    m_ResultAnim2 = AnimTextureHandle(GetHandle("RefineryWnd.RefineResultAnimation02.RefineResult2"));
    m_ResultAnim3 = AnimTextureHandle(GetHandle("RefineryWnd.RefineResultAnimation03.RefineResult3"));
    m_DragboxItem1 = ItemWindowHandle(GetHandle("RefineryWnd.ItemDragBox1Wnd.ItemDragBox1"));
    m_DragBoxItem2 = ItemWindowHandle(GetHandle("RefineryWnd.ItemDragBox2Wnd.ItemDragBox2"));
    m_DragBoxItem3 = ItemWindowHandle(GetHandle("RefineryWnd.ItemDragBox3Wnd.ItemDragBox3"));
    m_RefineryBtn = ButtonHandle(GetHandle("RefineryWnd.btnRefine"));
    m_UnRefineryBtn = ButtonHandle(GetHandle("RefineryWnd.btnUnRefine"));
    m_OkBtn = ButtonHandle(GetHandle("RefineryWnd.btnClose"));
    m_InstructionText = TextBoxHandle(GetHandle("RefineryWnd.txtInstruction"));
    m_RefText = TextBoxHandle(GetHandle("RefineryWnd.txtRef"));
    m_ResultAnim1.SetLoopCount(1);
    m_ResultAnim2.SetLoopCount(1);
    m_ResultAnim3.SetLoopCount(1);
    inventoryWndScript = InventoryWnd(GetScript("InventoryWnd"));
    return;
}

function OnShow()
{
    ResetReady();
    inventoryWndScript.HandleOpenWindow();
    return;
}

function ResetReady()
{
    procedure1stat = false;
    procedure2stat = false;
    procedure3stat = false;
    procedure4stat = false;
    m_GemstoneName = "";
    m_RefineryWnd_Main.ShowWindow();
    m_Highlight1.ShowWindow();
    m_Highlight2.HideWindow();
    m_Highlight3.HideWindow();
    m_SeletedItemHighlight1.HideWindow();
    m_SeletedItemHighlight2.HideWindow();
    m_SeletedItemHighlight3.HideWindow();
    m_ResultAnimation1.HideWindow();
    m_ResultAnimation2.HideWindow();
    m_ResultAnimation3.HideWindow();
    m_ResultAnim1.Stop();
    m_ResultAnim2.Stop();
    m_ResultAnim3.Stop();
    m_InstructionText.SetText(GetSystemMessage(1957));
    m_DragboxItem1.Clear();
    m_DragBoxItem2.Clear();
    m_DragBoxItem3.Clear();
    m_RefineryBtn.DisableWindow();
    m_UnRefineryBtn.DisableWindow();
    m_DragboxItem1.EnableWindow();
    m_DragBoxItem2.DisableWindow();
    m_DragBoxItem3.DisableWindow();
    PlaySound("ItemSound2.smelting.Smelting_dragin");
    m_OkBtn.EnableWindow();
    return;
}

function OnRefineryConfirmTargetItemResult()
{
    m_Highlight1.HideWindow();
    m_Highlight2.ShowWindow();
    m_Highlight3.HideWindow();
    m_SeletedItemHighlight1.ShowWindow();
    m_SeletedItemHighlight2.HideWindow();
    m_SeletedItemHighlight3.HideWindow();
    m_ResultAnimation1.HideWindow();
    m_ResultAnimation2.HideWindow();
    m_ResultAnimation3.HideWindow();
    procedure1stat = true;
    procedure2stat = false;
    procedure3stat = false;
    procedure4stat = false;
    m_InstructionText.SetText(GetSystemMessage(1958));
    m_DragboxItem1.EnableWindow();
    m_DragBoxItem2.EnableWindow();
    m_DragBoxItem3.DisableWindow();
    m_RefineryBtn.DisableWindow();
    return;
}

function OnRefineryConfirmRefinerItemResult()
{
    local string GemstoneName, Instruction;

    m_Highlight1.HideWindow();
    m_Highlight2.HideWindow();
    m_Highlight3.ShowWindow();
    m_SeletedItemHighlight1.ShowWindow();
    m_SeletedItemHighlight2.ShowWindow();
    m_SeletedItemHighlight3.HideWindow();
    m_ResultAnimation1.HideWindow();
    m_ResultAnimation2.HideWindow();
    m_ResultAnimation3.HideWindow();
    procedure1stat = true;
    procedure2stat = true;
    procedure3stat = false;
    procedure4stat = false;
    GemstoneName = Class'UIDATA_ITEM'.static.GetItemName(m_GemStoneClassID);
    m_GemstoneName = GemstoneName;
    Instruction = MakeFullSystemMsg(GetSystemMessage(1959), string(m_NecessaryGemstoneCount), GemstoneName);
    m_InstructionText.SetText(Instruction);
    m_DragboxItem1.EnableWindow();
    m_DragBoxItem2.EnableWindow();
    m_DragBoxItem3.EnableWindow();
    return;
}

function OnRefineryConfirmGemStoneResult()
{
    m_Highlight1.HideWindow();
    m_Highlight2.HideWindow();
    m_Highlight3.HideWindow();
    m_SeletedItemHighlight1.ShowWindow();
    m_SeletedItemHighlight2.ShowWindow();
    m_SeletedItemHighlight3.ShowWindow();
    m_ResultAnimation1.HideWindow();
    m_ResultAnimation2.HideWindow();
    m_ResultAnimation3.HideWindow();
    procedure1stat = true;
    procedure2stat = true;
    procedure3stat = true;
    procedure4stat = false;
    m_InstructionText.SetText(GetSystemMessage(1984));
    m_RefineryBtn.EnableWindow();
    return;
}

function OnRefineryRefineResult()
{
    m_Highlight1.HideWindow();
    m_Highlight2.HideWindow();
    m_Highlight3.HideWindow();
    m_ResultAnimation1.HideWindow();
    m_ResultAnimation2.HideWindow();
    m_ResultAnimation3.HideWindow();
    procedure1stat = true;
    procedure2stat = true;
    procedure3stat = true;
    procedure4stat = true;
    m_InstructionText.SetText(GetSystemMessage(1962));
    return;
}

function OnEvent(int a_EventID, string a_Param)
{
    switch(a_EventID)
    {
        // End:0x24
        case 2760:
            // End:0x21
            if(procedure1stat == false)
            {
                ShowRefineryInterface();
            }
            // End:0xC8
            break;
        // End:0x65
        case 2780:
            PlaySound("ItemSound2.smelting.Smelting_dragin");
            OnRefinerItemValidationResult(a_Param);
            // End:0xC8
            break;
        // End:0xA6
        case 2790:
            PlaySound("ItemSound2.smelting.Smelting_dragin");
            OnGemstoneValidationResult(a_Param);
            // End:0xC8
            break;
        // End:0xC2
        case 2800:
            OnRefineDoneResult(a_Param);
            ReloadLSGem();
            // End:0xC8
            break;
        // End:0xFFFF
        default:
            // End:0xC8
            break;
 
    }

}

function ShowRefineryInterface()
{
    ResetReady();
    return;
}

function OnDropItem(string a_WindowID, ItemInfo a_ItemInfo, int X, int Y)
{
    switch(a_WindowID)
    {
        // End:0x4E
        case "ItemDragBox1":
            // End:0x4B
            if(((procedure1stat == false) && procedure2stat == false) && procedure3stat == false)
            {
                ValidateFirstItem(a_ItemInfo);
            }
            // End:0xDF
            break;
        // End:0x95
        case "ItemDragBox2":
            // End:0x92
            if(((procedure1stat == true) && procedure2stat == false) && procedure3stat == false)
            {
                ValidateSecondItem(a_ItemInfo);
            }
            // End:0xDF
            break;
        // End:0xDC
        case "ItemDragBox3":
            // End:0xD9
            if(((procedure1stat == true) && procedure2stat == true) && procedure3stat == false)
            {
                ValidateGemstoneItem(a_ItemInfo);
            }
            // End:0xDF
            break;
        // End:0xFFFF
        default:
            break;
    }

}

function printRefInfo(ItemInfo Info)
{
    local string strDesc1, strDesc2, strDesc3, tmp;
    local int Quality;
    local Color a_Color;

    // End:0x47
    if(Info.SlotBitType == 8192)
    {
        Quality = Class'UIDATA_REFINERYOPTION'.static.GetQuality(Info.RefineryOp1);
        a_Color = GetRefineColor(Quality);        
    }
    else
    {
        Quality = Class'UIDATA_REFINERYOPTION'.static.GetQuality(Info.RefineryOp2);
        a_Color = GetRefineColor(Quality);
    }
    // End:0x18F
    if(Class'UIDATA_REFINERYOPTION'.static.GetOptionDescription(Info.RefineryOp1, strDesc1, strDesc2, strDesc3))
    {
        // End:0xCD
        if(-1 != InStr(strDesc1, "n"))
        {
            strDesc1 = Replace(strDesc1, "\\n", "");
        }
        // End:0xF8
        if(-1 != InStr(strDesc2, "n"))
        {
            strDesc2 = Replace(strDesc2, "\\n", "");
        }
        // End:0x123
        if(-1 != InStr(strDesc3, "n"))
        {
            strDesc3 = Replace(strDesc3, "\\n", "");
        }
        // End:0x147
        if(strDesc1 != "")
        {
            tmp = (tmp $ strDesc1) $ "\\n";
        }
        // End:0x16B
        if(strDesc2 != "")
        {
            tmp = (tmp $ strDesc2) $ "\\n";
        }
        // End:0x18F
        if(strDesc3 != "")
        {
            tmp = (tmp $ strDesc3) $ "\\n";
        }
    }
    // End:0x2A7
    if(Class'UIDATA_REFINERYOPTION'.static.GetOptionDescription(Info.RefineryOp2, strDesc1, strDesc2, strDesc3))
    {
        // End:0x1E5
        if(-1 != InStr(strDesc1, "n"))
        {
            strDesc1 = Replace(strDesc1, "\\n", "");
        }
        // End:0x210
        if(-1 != InStr(strDesc2, "n"))
        {
            strDesc2 = Replace(strDesc2, "\\n", "");
        }
        // End:0x23B
        if(-1 != InStr(strDesc3, "n"))
        {
            strDesc3 = Replace(strDesc3, "\\n", "");
        }
        // End:0x25F
        if(strDesc1 != "")
        {
            tmp = (tmp $ strDesc1) $ "\\n";
        }
        // End:0x283
        if(strDesc2 != "")
        {
            tmp = (tmp $ strDesc2) $ "\\n";
        }
        // End:0x2A7
        if(strDesc3 != "")
        {
            tmp = (tmp $ strDesc3) $ "\\n";
        }
    }
    m_RefText.SetTextColor(a_Color);
    m_RefText.SetText(tmp);
    // End:0x2ED
    if(tmp != "")
    {
        m_UnRefineryBtn.EnableWindow();        
    }
    else
    {
        m_UnRefineryBtn.DisableWindow();
    }
    return;
}

function ValidateFirstItem(ItemInfo a_ItemInfo)
{
    // End:0x24
    if((a_ItemInfo.ItemType != 0) || a_ItemInfo.CrystalType <= 0)
    {
        return;
    }
    RefineItemInfo = a_ItemInfo;
    m_TargetItemServerID = a_ItemInfo.ServerID;
    OnItemValidation(a_ItemInfo.ServerID);
    return;
}

function OnItemValidation(int Item1ServerID)
{
    // End:0x53
    if(Item1ServerID == RefineItemInfo.ServerID)
    {
        // End:0x42
        if(!m_DragboxItem1.SetItem(0, RefineItemInfo))
        {
            m_DragboxItem1.AddItem(RefineItemInfo);
        }
        printRefInfo(RefineItemInfo);
        OnRefineryConfirmTargetItemResult();
    }
    return;
}

function ValidateSecondItem(ItemInfo a_ItemInfo)
{
    LifeStoneItemInfo = a_ItemInfo;
    m_RefineItemServerID = a_ItemInfo.ServerID;
    Class'RefineryAPI'.static.ConfirmRefinerItem(m_TargetItemServerID, m_RefineItemServerID);
    return;
}

function OnRefinerItemValidationResult(string a_Param)
{
    local int Item2ServerID, Item2ClassID, ItemValidationResult2, RequiredGemstoneAmount, RequiredGemstoneClassID;

    ParseInt(a_Param, "RefinerItemServerID", Item2ServerID);
    ParseInt(a_Param, "RefinerItemClassID", Item2ClassID);
    ParseInt(a_Param, "Result", ItemValidationResult2);
    ParseInt(a_Param, "GemStoneCount", RequiredGemstoneAmount);
    ParseInt(a_Param, "GemStoneClassID", RequiredGemstoneClassID);
    m_GemStoneClassID = RequiredGemstoneClassID;
    m_NecessaryGemstoneCount = RequiredGemstoneAmount;
    switch(ItemValidationResult2)
    {
        // End:0x118
        case 1:
            // End:0x115
            if(Item2ServerID == LifeStoneItemInfo.ServerID)
            {
                texCountNoStack(LifeStoneItemInfo);
                // End:0x10F
                if(!m_DragBoxItem2.SetItem(0, LifeStoneItemInfo))
                {
                    m_DragBoxItem2.AddItem(LifeStoneItemInfo);
                }
                OnRefineryConfirmRefinerItemResult();
            }
            // End:0x122
            break;
        // End:0x11F
        case 0:
            // End:0x122
            break;
        // End:0xFFFF
        default:
            break;
    }

}

function ValidateGemstoneItem(ItemInfo a_ItemInfo)
{
    GemstoneItemInfo = a_ItemInfo;
    m_GemStoneServerID = a_ItemInfo.ServerID;
    // End:0x55
    if(a_ItemInfo.ItemNum >= m_NecessaryGemstoneCount)
    {
        Class'RefineryAPI'.static.ConfirmGemStone(m_TargetItemServerID, m_RefineItemServerID, m_GemStoneServerID, m_NecessaryGemstoneCount);        
    }
    else
    {
        Class'RefineryAPI'.static.ConfirmGemStone(m_TargetItemServerID, m_RefineItemServerID, m_GemStoneServerID, a_ItemInfo.ItemNum);
    }
    return;
}

function OnGemstoneValidationResult(string a_Param)
{
    local int Item3ServerID, Item3ClassID, ItemValidationResult3, RequiredMoreGemstoneAmount, GemstoneAmountChecked;

    Debug("����° �̺�Ʈ ����:������");
    ParseInt(a_Param, "GemStoneServerID", Item3ServerID);
    ParseInt(a_Param, "GemStoneClassID", Item3ClassID);
    ParseInt(a_Param, "Result", ItemValidationResult3);
    ParseInt(a_Param, "NecessaryGemStoneCount", RequiredMoreGemstoneAmount);
    ParseInt(a_Param, "GemStoneCount", GemstoneAmountChecked);
    m_GemStoneClassID = Item3ClassID;
    m_NecessaryGemstoneCount = GemstoneAmountChecked;
    switch(ItemValidationResult3)
    {
        // End:0x15F
        case 1:
 
            if(!m_DragBoxItem3.SetItem(0, GemstoneItemInfo))
            {
                GemstoneItemInfo.ItemNum = GemstoneAmountChecked;
                m_DragBoxItem3.AddItem(GemstoneItemInfo);
                OnRefineryConfirmGemStoneResult();
        
  
                }
				  break;
		              // End:0x166
                case 0:
                    // End:0x169
                    break;
                    // End:0xFFFF
                    default:
                        return;
                        break;		
				
				
				
				
     
            }


}

function OnClickButton(string strID)
{
    switch(strID)
    {
        // End:0x49
        case "btnRefine":
            PlaySound("Itemsound2.smelting.smelting_loding");
            OnClickRefineButton();
            // End:0x7B
            break;
        // End:0x62
        case "btnUnRefine":
            OnUnRefineRequest();
            // End:0x7B
            break;
        // End:0x78
        case "btnClose":
            OnClickCancelButton();
            // End:0x7B
            break;
        // End:0xFFFF
        default:
            break;
    }
    return;
}

function OnClickCancelButton()
{
    m_RefineryWnd_Main.HideWindow();
    PlaySound("Itemsound2.smelting.smelting_dragout");
    procedure1stat = false;
    procedure2stat = false;
    procedure3stat = false;
    procedure4stat = false;
    return;
}

function OnClickRefineButton()
{
    m_Highlight1.HideWindow();
    m_Highlight2.HideWindow();
    m_Highlight3.HideWindow();
    m_ResultAnimation1.HideWindow();
    m_ResultAnimation2.HideWindow();
    m_ResultAnimation3.HideWindow();
    procedure1stat = true;
    procedure2stat = true;
    procedure3stat = true;
    procedure4stat = true;
    OnRefineRequest();
    return;
}

function OnTextureAnimEnd(AnimTextureHandle a_WindowHandle)
{
    switch(a_WindowHandle)
    {
        // End:0x0F
        case m_ResultAnim1:
        // End:0x17
        case m_ResultAnim2:
        // End:0x28
        case m_ResultAnim3:
            OnResultAnimEnd();
            // End:0x2B
            break;
        // End:0xFFFF
        default:
            break;
    }

}

function OnResultAnimEnd()
{
    m_ResultAnimation1.HideWindow();
    m_ResultAnimation2.HideWindow();
    m_ResultAnimation3.HideWindow();
    return;
}

function bool GetItemInfo(int Id, out ItemInfo Info)
{
    local int Index;
    local ItemInfo clnInfo;
    local InventoryWnd m_scriptInventoryWnd;

    m_scriptInventoryWnd = InventoryWnd(GetScript("InventoryWnd"));
    Index = m_scriptInventoryWnd.m_invenItem.FindItemWithClassID(Id);
    m_scriptInventoryWnd.m_invenItem.GetItem(Index, Info);
    // End:0x78
    if(Info != clnInfo)
    {
        return true;
    }

}

function ReloadLSGem()
{
    local ItemInfo Stone, Gems;

    // End:0x64
    if(GetItemInfo(LifeStoneItemInfo.ClassID, Stone))
    {
        m_RefineItemServerID = Stone.ServerID;
        texCountNoStack(Stone);
        // End:0x61
        if(!m_DragBoxItem2.SetItem(0, Stone))
        {
            m_DragBoxItem2.AddItem(Stone);
        }        
    }
    else
    {
        m_DragBoxItem2.Clear();
    }
    // End:0xBC
    if(GetItemInfo(GemstoneItemInfo.ClassID, Gems))
    {
        // End:0xB9
        if(!m_DragBoxItem3.SetItem(0, Gems))
        {
            m_DragBoxItem3.AddItem(Gems);
        }        
    }
    else
    {
        m_DragBoxItem3.Clear();
    }
    return;
}

function OnRefineRequest()
{
    // End:0x58
    if((m_DragBoxItem2.GetItemNum() > 0) || m_DragBoxItem3.GetItemNum() >= m_NecessaryGemstoneCount)
    {
        // End:0x58
        if((RefineItemInfo.RefineryOp1 > 0) || RefineItemInfo.RefineryOp1 > 0)
        {
            OnUnRefineRequest();
        }
    }
    Class'RefineryAPI'.static.RequestRefine(m_TargetItemServerID, m_RefineItemServerID, m_GemStoneServerID, m_NecessaryGemstoneCount);
    return;
}

function OnUnRefineRequest()
{
    m_RefText.SetText("");
    m_UnRefineryBtn.DisableWindow();
    Class'RefineryAPI'.static.RequestRefineCancel(m_TargetItemServerID);
    RefineItemInfo.RefineryOp1 = 0;
    RefineItemInfo.RefineryOp2 = 0;
    // End:0x7A
    if(!m_DragboxItem1.SetItem(0, RefineItemInfo))
    {
        m_DragboxItem1.AddItem(RefineItemInfo);
    }
    PlayResultAnimation(EInterfaceSoundType(1));

}

function OnRefineDoneResult(string a_Param)
{
    local int Option1, Option2, RefineResult, Quality;

    ParseInt(a_Param, "Option1", Option1);
    ParseInt(a_Param, "Option2", Option2);
    ParseInt(a_Param, "Result", RefineResult);
    m_OkBtn.EnableWindow();
    switch(RefineResult)
    {
        // End:0x114
        case 1:
            RefineItemInfo.RefineryOp1 = Option1;
            RefineItemInfo.RefineryOp2 = Option2;
            // End:0xB2
            if(!m_DragboxItem1.SetItem(0, RefineItemInfo))
            {
                m_DragboxItem1.AddItem(RefineItemInfo);
            }
            printRefInfo(RefineItemInfo);
            OnRefineryRefineResult();
            Quality = Class'UIDATA_REFINERYOPTION'.static.GetQuality(Option2);
            // End:0xF2
            if(0 >= Quality)
            {
                Quality = 1;                
            }
            else
            {
                // End:0x106
                if(4 < Quality)
                {
                    Quality = 4;
                }
            }
            PlayResultAnimation(Quality);
            // End:0x124
            break;
        // End:0x121
        case 0:
            OnClickCancelButton();
            // End:0x124
            break;
        // End:0xFFFF
        default:
            break;
    }

}

function PlayResultAnimation(int grade)
{
    m_ResultAnim1.SetLoopCount(1);
    m_ResultAnim2.SetLoopCount(1);
    m_ResultAnim3.SetLoopCount(1);
    switch(grade)
    {
        // End:0x87
        case 1:
            m_ResultAnimation1.ShowWindow();
            PlaySound("ItemSound2.smelting.smelting_finalB");
            m_ResultAnim1.Play();
            // End:0x1B9
            break;
        // End:0xD8
        case 2:
            m_ResultAnimation2.ShowWindow();
            PlaySound("ItemSound2.smelting.smelting_finalC");
            m_ResultAnim2.Play();
            // End:0x1B9
            break;
        // End:0x129
        case 3:
            m_ResultAnimation3.ShowWindow();
            PlaySound("ItemSound2.smelting.smelting_finalD");
            m_ResultAnim3.Play();
            // End:0x1B9
            break;
        // End:0x1B6
        case 4:
            m_ResultAnimation1.ShowWindow();
            m_ResultAnimation2.ShowWindow();
            m_ResultAnimation3.ShowWindow();
            PlaySound("ItemSound2.smelting.smelting_finalD");
            m_ResultAnim1.Play();
            m_ResultAnim2.Play();
            m_ResultAnim3.Play();
            // End:0x1B9
            break;
        // End:0xFFFF
        default:
            break;
    }

}